"""empty message

Revision ID: 15dbadfbb7ba
Revises: 
Create Date: 2019-01-07 09:23:55.399963

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15dbadfbb7ba'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fa_question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Type', sa.String(), nullable=False),
    sa.Column('Question', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.String(), nullable=False),
    sa.Column('user_msg', sa.String(), nullable=False),
    sa.Column('user_sid', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_cart',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('equipment', sa.String(), nullable=True),
    sa.Column('pricing', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rma',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site', sa.String(length=60), nullable=False),
    sa.Column('serialnumber', sa.String(length=25), nullable=False),
    sa.Column('rmanumber', sa.String(length=50), nullable=False),
    sa.Column('Vendor', sa.String(length=50), nullable=False),
    sa.Column('Issue', sa.Text(), nullable=True),
    sa.Column('Date_Sent', sa.String(length=50), nullable=False),
    sa.Column('Date_Received', sa.String(length=50), nullable=True),
    sa.Column('Rep', sa.String(length=50), nullable=True),
    sa.Column('Notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rmanumber'),
    sa.UniqueConstraint('serialnumber')
    )
    op.create_table('sites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sitename', sa.String(), nullable=False),
    sa.Column('contractstart', sa.String(), nullable=False),
    sa.Column('contractend', sa.String(), nullable=False),
    sa.Column('hwkey', sa.String(), nullable=False),
    sa.Column('stations', sa.String(), nullable=False),
    sa.Column('printers', sa.String(), nullable=False),
    sa.Column('remprinters', sa.String(), nullable=False),
    sa.Column('bof', sa.Boolean(), nullable=True),
    sa.Column('processor', sa.String(), nullable=False),
    sa.Column('giftopt', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site', sa.String(), nullable=True),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=60), nullable=False),
    sa.Column('adminstatus', sa.Boolean(), nullable=True),
    sa.Column('sitelink', sa.Integer(), nullable=True),
    sa.Column('sid', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['sitelink'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('sites')
    op.drop_table('rma')
    op.drop_table('order_cart')
    op.drop_table('messages')
    op.drop_table('fa_question')
    # ### end Alembic commands ###
