"""empty message

Revision ID: 260f55968ae0
Revises: 
Create Date: 2019-01-11 07:59:33.955330

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '260f55968ae0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ticket',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ticket')
    # ### end Alembic commands ###
