"""empty message

Revision ID: 621182d8b0a0
Revises: 77b0d2ac1c1e
Create Date: 2019-01-07 00:23:38.826441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '621182d8b0a0'
down_revision = '77b0d2ac1c1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('sid', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'sid')
    # ### end Alembic commands ###
