"""empty message

Revision ID: 77b0d2ac1c1e
Revises: 
Create Date: 2019-01-06 21:55:19.048632

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77b0d2ac1c1e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_column('rma', 'Customer')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rma', sa.Column('Customer', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('site', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('username', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=60), autoincrement=False, nullable=False),
    sa.Column('adminstatus', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('sitelink', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['sitelink'], ['sites.id'], name='user_sitelink_fkey'),
    sa.PrimaryKeyConstraint('id', name='user_pkey'),
    sa.UniqueConstraint('email', name='user_email_key'),
    sa.UniqueConstraint('username', name='user_username_key')
    )
    # ### end Alembic commands ###
