"""empty message

Revision ID: 84e4fdbfc004
Revises: 
Create Date: 2019-01-22 15:43:44.503367

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84e4fdbfc004'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket', sa.Column('issue', sa.String(), nullable=True))
    op.add_column('ticket', sa.Column('message', sa.String(), nullable=True))
    op.add_column('ticket', sa.Column('site', sa.String(), nullable=True))
    op.add_column('ticket', sa.Column('user', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ticket', 'user')
    op.drop_column('ticket', 'site')
    op.drop_column('ticket', 'message')
    op.drop_column('ticket', 'issue')
    # ### end Alembic commands ###
