"""empty message

Revision ID: ada2899b240f
Revises: 
Create Date: 2018-12-31 10:58:04.482980

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ada2899b240f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sites', 'sitename',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sites', 'sitename',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
