"""empty message

Revision ID: d0808ecb8f74
Revises: 84e4fdbfc004
Create Date: 2019-01-23 09:03:10.382753

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0808ecb8f74'
down_revision = '84e4fdbfc004'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket', sa.Column('recipient', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ticket', 'recipient')
    # ### end Alembic commands ###
