"""empty message

Revision ID: e6f6d2ae4a8a
Revises: 
Create Date: 2019-01-03 00:20:50.498159

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6f6d2ae4a8a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rma', 'Customer')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rma', sa.Column('Customer', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
